[package]
name = "cherry-quickjs"
version = "0.0.1"
edition = "2024"

[dependencies]
llrt_buffer = "0.8.1-beta"
llrt_fetch = "0.8.1-beta"
llrt_fs = "0.8.1-beta"
llrt_path = "0.8.1-beta"
llrt_timers = "0.8.1-beta"
rquickjs = { version = "0.11", features = ["loader", "futures"] }
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["rt", "macros", "time", "net"] }
ureq = "3.3.0"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[build-dependencies]
rquickjs = { version = "0.11", features = ["loader", "futures"] }
